config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'title', to: 'tasks#title', as :title

  get    "tasks/new",      to: "tasks#new", as: :tasknew
  post   "tasks",          to: "tasks#create"

  # NB: The `show` route needs to be *after* `new` route.
  get 'tasks', to: 'tasks#index'
  root to: 'pages#home'
  get 'tasks/:id', to: 'tasks#show', as: :task

  get    "tasks/:id/edit", to: "tasks#edit", as: :taskedit # => form
  patch  "tasks/:id",      to: "tasks#update" # => sends inputs

  delete "tasks/:id",      to: "tasks#destroy", as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :update, :edit, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def home
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    # => Whitelisting
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <link rel=“stylesheet” href=“https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css“>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a new task</h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.check_box :completed %>
  </div>


  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to "All tasks", tasks_path(@tasks) %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>


<% @tasks.each do |task| %>
  <% if task.completed  %>
    <p>✅<%= link_to task.title, task_path(task) %></p>
    <%= link_to "Delete", delete_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
    <% else %>
    <p>❌<%= link_to task.title, task_path(task) %></p>
    <%= link_to "Delete", delete_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
  <% end %>
<% end %>


<%=  link_to "Create a new task", tasknew_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to "All tasks", tasks_path(@tasks) %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>

<p><%= @task.completed %></p>

<%= link_to "Edit task", taskedit_path %>

<%= link_to "All tasks", tasks_path(@tasks) %>